### ISSUE TITLE
Add Future Snow Projections datasets

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/cloud-optimized-data-pipelines#237] opened 2022-11-16 14:58 UTC
- [x] Identify the point of contact and ensure someone is providing them updates: Justin Pflug / @j08lue 
- [x] Use case: I’m most-interested in giving the public ‘Exploration’ capabilities and letting them toggle on/off the snow projections for different periods/dates/emissions.
- [x] Data provider has read [guidelines on data preparation](https://github.com/NASA-IMPACT/veda-workflows-api/blob/main/how-to.md#prepare-the-data)
- [x] Identify data location: `s3://veda-data-store-staging/EIS/snowProjections/`
   - File naming conventions for historical data: `<DOMAIN>_SWE_tavg_historical_2011<MONTH><DAY>.cog.tif`
   - File naming conventions for future periods: `<DOMAIN>_SWE_tavg_<PROJECTION>_<YEAR><MONTH><DAY>_median.cog.tif`
   - File naming conventions for future percent-changes in snow water equivalent: `<DOMAIN>_SWE_tavg_<PROJECTION>_<YEAR><MONTH><DAY>_percChange.cog.tif`
   - DOMAIN: Cascades (CSCD), Northern-Rockies West (NORW), Northern Rockies (NOR), Mid-Rockies (MIR), and Southern Rockies (SOR)
   - PROJECTION: emissions scenarios (different representations of future warming) SSP2-4.5 (ssp245) and SSP5-8.5 (ssp585)
   - YEAR: years that fall within the 20-year periods listed above are representative of the 20-year medians
   - Note: We have two days annually (Apr and May 1st) for 5 periods (historic, and 4 future timeframes)
- [x] Number of items: 170
- [x] Verify that files are valid COGs (e.g. with [`rio cogeo validate`](https://cogeotiff.github.io/rio-cogeo/Is_it_a_COG/#3-cog-validation))
- [x] Gather STAC collection metadata

  - id: `snow-projections`
  - title: `Future Snow Projections`
  - description: `Historic and projected Snow Water Equivalent (SWE), and percent-change in SWE, generated using the Land Information System Framework and NASA Earth Exchange downscaled CMIP6 climate projections`
  - license: `Creative Commons Zero ([CC0-1.0](https://spdx.org/licenses/CC0-1.0.html))`
  - temporal interval: `1995-04-01` to `2095-05-01`. Only April 1st and May 1st dates, representative of median snowpack across 20-year periods (1995 – 2014, 2016 – 2035, 2036 – 2055, 2056 – 2075, and 2076 – 2095)
  - whether it is periodic on the dashboard (periodic = regular time series of layers without gaps): `false`
  - the dashboard time density: `null`

- [x] Review and follow https://github.com/NASA-IMPACT/cloud-optimized-data-pipelines/blob/main/OPERATING.md
- [x] Open PR for publishing those datasets to the Staging API:
- [ ] Notify QA / move ticket to QA state
- [ ] Once approved, merge and close.

## Resources on metadata

If not already familiar with these conventions for generating STAC collection and item metadata:
       - Collections: https://github.com/NASA-IMPACT/delta-backend/issues/29 and STAC version 1.0 specification for collections
       - Items: https://github.com/NASA-IMPACT/delta-backend/issues/28 and STAC version 1.0 specification for items
       - NOTE: The delta-backend instructions are specific to datasets for the climate dashboard, however not all datasets are going to be a part of the visual layers for the dashboard so you can ignore the instructions that are specific to "dashboard" extension, "item_assets" in the collection and "cog_default" asset type in the item.

**Comment by jupflug** [comment] 2022-11-21 21:24
The STAC collection metadata above should now be complete, and all the data is up on the veda data store staging directory (in COG format). I updated the checklist above.

I don't think I have username/password access to the API for ingesting the data. @j08lue, is that something you and your team is doing?

**Comment by j08lue** [comment] 2022-11-21 21:55
Thanks, @jupflug!

> I don't think I have username/password access to the API for ingesting the data. @j08lue, is that something you and your team is doing?

Yes, up until now the team takes care of setting up the STAC collection and creating and adding the records. We hope to give you an interface to do that conveniently at some point. Once the data is in STAC, either you or we can create a pull request to configure them in the VEDA Dashboard.

I will put this ticked on our backlog and see when we can pick it up. We have had a lot of ingestions lately and would like to focus on other things in the next sprint as much as possible. But we can perhaps iterate this ticket on the side - I am sure we will need you to verify the information once we start creating the records.

> all the data is up on the veda data store staging directory (in COG format)

Can you please tell us how you created the COGs, @jupflug? Did you use `rio cogeo create`, if so, in which version and with which parameters? Did you pay attention to the rasters having a `NoData` flag before you cloud-optimized them and did you choose the `--overview-resampling` carefully? Those are the most common issues, which we often only encounter once the data is already in the Dashboard and you look at the internal overviews.

You can also use our online COG viewer to have a look at how your data renders: https://staging-raster.delta-backend.com/cog/validate?url=s3://veda-data-store-staging/EIS/snowProjections/CSCD_SWE_tavg_historical_20110401.cog.tif - I tried to guess one of your file names but this one did not work. Pls pick a valid one.

**Comment by jupflug** [comment] 2022-11-21 22:56
The original tiffs I have did not have nodata values specified, so I created the COGs using `rio cogeo create <input>.tif <output>.tif --nodata 0`, and rio version 1.3.4. Is any specific resampling required? Currently, they should all be using nearest-neighbor.

That pathname should be correct, but the COG renderer doesn't seem to be working for my data. That being said, I can't get any of the other data from other EIS projects to render either.

**Comment by j08lue** [comment] 2022-11-22 11:03
> I created the COGs using `rio cogeo create <input>.tif <output>.tif --nodata 0`, and rio version 1.3.4

nice, thanks

> Is any specific resampling required?

Not required and `nearest` is probably good enough most of the time. For continuous variables, in principle, `average` overviews better reflect the data that went into the aggregate. For categorical data, `mode` can be good, reflecting the most prominent class in the aggregation region rather than the one `nearest` to the center. But it depends on the dataset.

> the COG renderer doesn't seem to be working for my data

Right, I can confirm that calls that used to work do not anymore, so there must be something wrong with the service. I'll raise this and let you know when it is fixed.

**Comment by jupflug** [comment] 2022-11-28 22:51
Hi @j08lue. Some colleagues wanted %-difference maps in addition to the SWE maps. I added these COGs to the veda bucket and updated the data information at the beginning of this issue thread. I also did some cross-checks with other COG data on veda, and it looks like my data should be ready to go. 

Is there anything I can this week do to help get this pushed over?

**Comment by j08lue** [comment] 2022-12-01 12:44
Great, thanks for the ping, @jupflug - sorry for the slow response from me.

The next step is to open a pull request in this repo that creates the collection metadata and the inputs to the step function, as described in the [Operations Guide](https://github.com/NASA-IMPACT/veda-data-pipelines/blob/main/OPERATING.md). If you could open that PR, that would be great.

We are currently prioritizing to develop a more self-service data ingestion system for you, so the team is not actively tracking these ingestion tickets. Please let us know if anything is urgent, then we will try to find someone to take over. If you could start that PR, that would certainly accelerate the process, even if you just push stubs to start with.

**Comment by jupflug** [comment] 2022-12-01 16:13
Thanks for your help @j08lue, and sorry for my confusion on this process. I created a pull request with the json data and step function inputs corresponding to the snow maps, and snow-difference maps. Let me know if you need anything else for me.

Ideally, I would like to have some simple visualizations up so I can promote these outputs for the AGU meeting Dec 12 - 16.

**Comment by smohiudd** [comment] 2022-12-05 19:55
Thanks @jupflug. I'll review the the PR and will get started on the ingest process. Will try and prioritize to make your Dec 12 deadline.

**Comment by jupflug** [comment] 2022-12-07 14:28
Thanks for your help @smohiudd! I saw this was merged this morning.

What should be my next steps for getting this data in a dashboard-viewable format? I believe @j08lue told me that once the data is up, we will open a pull request for the configuration. Should I be starting this, and if so, should the pull request be on the `veda-config` repository?

**Comment by jupflug** [comment] 2022-12-08 17:17
Sounds good. Thanks for your help @smohiudd. I have a veda-config fork [here](https://github.com/jupflug/veda-config) that seems to render just fine for me locally, it's just missing the data. 

Please let me know when the data is up, or if you need anything else from me. I'll take out a pull request once I'm sure the data-vis is working correctly.

**Comment by smohiudd** [comment] 2022-12-08 17:19
I loaded the data to the dev environment. You can view the stac collections here:

https://radiantearth.github.io/stac-browser/#/external/dev-stac.delta-backend.com/collections/snow-projections-diff
https://radiantearth.github.io/stac-browser/#/external/dev-stac.delta-backend.com/collections/snow-projections-median

Let me know if you see any issues. If, not I can start to load into the `staging` environment.

**Comment by jupflug** [comment] 2022-12-08 17:34
@smohiudd I don't see any issues! I think we should be ready to get this staged.

**Comment by smohiudd** [comment] 2022-12-08 20:20
@jupflug, the COGs looks good in dev. Here are the diff projections. 

![Image](https://user-images.githubusercontent.com/34844565/206559120-dec3c682-dd19-4a12-866d-68ef6bdbe5c1.png)

Also, can you initiate a pull request for your branch in `veda-config`

**Comment by jupflug** [comment] 2022-12-08 20:32
Great! One potential issue, many of the red grid cells from your screenshot above should be nodata values (-9999). Can we keep those from showing up in the visualization? Sorry in advance if that is an option I missed somewhere.

I initiated a pull request in veda-config (Feature/add snow projections #166). Please let me know what else you need from me.

**Comment by j08lue** [comment] 2022-12-08 20:50
Hmm, ideally the COGs would have a `nodata` flag that tell the software that you are using that value as a fill value. If you do not have that, chances are that any reprojection or the COG overviews (coarse versions of the data to be read when zoomed out) are polluted with the fill values.

If your file does not have that value, you can in principle pass that to [TiTiler](https://developmentseed.org/titiler/endpoints/cog/) (`?nodata=-9999`) via the config TiTiler options. But if the overviews are polluted, that won't help. Then you have to take the files, set the nodata flag, and then build new overviews (cloud-optimize again). https://github.com/NASA-IMPACT/veda-workflows-api/blob/7fbdba54a44ebe6bd105153fe606469b87b9611f/how-to.md#creating-cogs

**Comment by jupflug** [comment] 2022-12-08 21:14
Thanks @j08lue and @smohiudd. I just did a double-check on the swe-difference cog files, and the no-data values are specified as -9999. QGIS also recognizes this and doesn't fill those gridcells. 

It makes me thing that the issue is with that rescaling since 0 is the no-data value for the median snow projection data, and 0 is included in the rescaling on that dataset (rescale: 0 to 1000). It's going to do weird things to the colormap, but does it recognize the no-data values if we change the lower limit to -9999?

**Comment by vincentsarago** [comment] 2022-12-08 21:29
@jupflug I don't think I have direct access to the data, I'm not directly involved on the project so I have no idea where the bucket is 😄. If it is possible to share the file directly I could have a look tomorrow

**Comment by smohiudd** [comment] 2022-12-08 22:17
Thanks @vincentsarago for your help with this. I added one sample to this bucket: s3://climatedashboard-data/snowProjections/SOR_SWE_tavg_ssp585_20770401_percChange.cog.tif. I'll also send you a copy on slack if you don't have access to the bucket

**Comment by smohiudd** [comment] 2022-12-09 15:16
Thanks @vincentsarago for your help with this yesterday. Vincent noticed that that the actual nodata values in the COG itself are NaN values, not -9999. 

From Vincent:
<img width="929" alt="image" src="https://user-images.githubusercontent.com/34844565/206732888-e9a6a84b-41b0-412f-b760-7d15753b74f1.png">

I ran the dashboard with `nodata: nan` under `sourceParams` and looks like it's working fine now.

![image](https://user-images.githubusercontent.com/34844565/206732440-fbbcf124-a0a5-42b8-b413-9ad0ab20949a.png)

Vincent also noticed that  the bounding box for the one COG sample I sent is shown as `-108.67498779296875, 40.28500091552662, -105.40498779296708, 36.66500091552734`

It should be in form of `xmin, ymin, xmax, ymax` but in the example above is showing up as `xmin, ymax, xmax, ymin`. @jupflug do you know about how the bounding box was set?

**Comment by jupflug** [comment] 2022-12-09 15:51
Thanks for your help @smohiudd and @vincentsarago, and sorry for all the issues. I'm not sure why the nodata is appearing as nan values, but thanks for figuring that out!

It also looks like the tiffs I used to generate the cog files are also flipped. I used xesmf to regrid our model outputs from curvilinear to rectilinear coordinate systems. From what I can tell it looks like these were read-in with lat[0] being the maximum latitude, and lat[-1] being the minimum latitude (upside-down). However, since the raster data itself is also flipped, it is still correctly georeferenced. 

It looks like it's playing nicely with the dashboard. Do you need me to fix it at this point? We have some plans to develop some discoveries and more visualizations once we get through AGU, so I can also include those corrections in the next round of developments if that would be easiest.

**Comment by smohiudd** [comment] 2022-12-09 19:20
No worries @jupflug, It was an easy fix on the dashboard once we knew what to do. 

I _think_ we should be ok with the existing COGs as is but let me defer product owner @j08lue about this as well. These COGs could be re-created and re-uploaded in your next round of datasets.

**Comment by jupflug** [comment] 2022-12-09 21:49
Thanks @smohiudd! I present a poster on this data Monday morning, so I'd love to have folks be able to visualize the data if at all possible. Is there anything you need me to do on my end at this time?

**Comment by smohiudd** [comment] 2022-12-09 21:52
@jupflug, I'm just finishing up the ingestion into the staging environment right now and then will approve the pull request. I think we should be on track to have this running well before Monday. Will update you again in a couple hours.

**Comment by smohiudd** [comment] 2022-12-09 23:38
I merged the veda-config PR to `develop` but the dashboard team needs release to production. @danielfdsilva can you help with this? This dataset needs to be up before Monday Dec 12 for the AGU conference.

**Comment by smohiudd** [comment] 2022-12-09 23:48
@jupflug, while we are waiting for release to production you can use this preview https://develop--visex.netlify.app/eis/datasets which includes the snow projection datasets.

**Comment by jupflug** [comment] 2022-12-10 00:57
Thanks @smohiudd! This looks really good. I think this will be perfect to introduce the data and let folks visualize our outputs. Thanks for all your help with this. One quick question, I noticed that there is no option to select/toggle the SSP5-8.5 (filenames `*ssp585*<YYYY>*cog.tif`) or SSP2-4.5 (`*ssp245*<YYYY>*cog.tif`) scenarios. Do you know which is being displayed, and is it consistent for the different years?

I'm good with releasing what we currently have, but I have a number of things I could work on once we get through AGU (including the COG extents issue). Should I raise a new issue on veda-config for those changes in the future, or should we keep the discussion on this thread?

Thanks again for your help, and with fast-tracking this.

**Comment by smohiudd** [comment] 2022-12-10 06:25
@jupflug, Ok I understand now that you are using two different emission scenarios. Right now, the way it's configured in the pipeline is all in one STAC collection. So if you want to differentiate and toggle between scenarios you'll need a STAC collection for each scenario. So I propose we have three collections: ssp585, ssp245 and historical average. I can quickly run the ingest again in dev with the new collections and see how it looks in config.

The way it is right now I'm not sure which scenario it's pulling. It might just be the first item that gets returned from the database that meets the datetime filter.

**Comment by j08lue** [comment] 2022-12-10 08:14
Great you got the data published in time, @jupflug and @smohiudd.

> Should I raise a new issue on veda-config for those changes in the future, or should we keep the discussion on this thread?

New issues (referencing this one) would be great, thanks.

**Comment by jupflug** [comment] 2022-12-10 14:41
@smohiudd that sounds good! However if it's consistently grabbing one scenario instead of the other, then we could keep what we currently have. I have to print my poster today so I was hoping to include a link to this. 

One note: the snow projections difference data don't have the "historical" since the differences are relative to the historical time frame. 

Thanks @j08lue! I'll close this issue when we make this last change.

**Comment by j08lue** [comment] 2022-12-10 15:04
@jupflug the links are predictable, so you could print them already and then we re-ingest the data into two collections. I think we can get that done by end of day Monday, but I cannot promise that on behalf of the team.

**Comment by j08lue** [comment] 2022-12-10 15:08
Something like 

* `https://visex.netlify.app/eis/datasets/snow-projections-diff-ssp585` and
* `https://visex.netlify.app/eis/datasets/snow-projections-diff-ssp245`

or so?

**Comment by jupflug** [comment] 2022-12-10 15:20
Got it! Thanks that's helpful to know. 

Maybe I misunderstood, but this makes it look like the SSP2-4.5 and SSP5-8.5 scenarios would be to be two different "Datasets" on the dashboard. Would it instead be possible to instead add a toggle, like the "toggle date comparison" to compare the two different emissions scenarios for a single date (within one dataset explorer)? I've been looking through [here](https://github.com/NASA-IMPACT/veda-config/blob/develop/docs/MDX_BLOCKS.md) and it looks like the compare option is only for dates.

**Comment by smohiudd** [comment] 2022-12-10 16:06
SSP2-4.5 and SSP5-8.5 would be two different collections in the backend however as far as the visualization/dashboard is concerned, they would be on one dataset page - either Projection of SWE or Projections of SWE Losses. I was thinking they could be presented similar to how we do CO2: https://visex.netlify.app/eis/datasets/co2/explore?position=0%7C0%7C1&datetime=2022-02-13T00%3A00%3A00.000Z.

Also @j08lue is correct you can just use the https://visex.netlify.app/ and any changes between now and Monday will be reflected there.

**Comment by smohiudd** [comment] 2022-12-11 21:05
Here is the [updated dashboard](https://deploy-preview-169--visex.netlify.app/) with the SSP2-4.5 and SSP5-8.5 scenarios. @jupflug, can you let me know if this is ok or if you have any suggested changes? After that I'll merge to `develop` and you should be able to see everything on https://visex.netlify.app/

**Comment by jupflug** [comment] 2022-12-11 22:18
@smohiudd, this looks great. I think this is perfect for what we were hoping to communicate this week. We have another conference early-January, and then I'll follow up with some additional commits after that. Thanks again for your help!

**Closed as completed** 2022-12-12 20:56 UTC
Labels: dataset
